AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-application

  Sample SAM Template for serverless-application

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 2048

Resources:
  UserCreate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/
      Handler: create.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        UserCreatePostAPI:
          Type: Api
          Properties:
            Path: /users/
            Method: post
  UsersRetrieveById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/
      Handler: read.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        UsersRetrieveByIdGetAPI:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: get

  UsersUpdateById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/
      Handler: update.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        UsersUpdateByIdPutAPI:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: put
